/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:ca642fe5-e9a8-4623-b985-727e330e2d54",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_tUCliGte0",
    "aws_user_pools_web_client_id": "5g4d8lrhnfh2742r4pl3ufh3qv",
    "oauth": {}
};


export default awsmobile;
